name: Build Ontologies
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install tox

      - name: Create local changes
        id: update
        run: |
          tox -e py
        env:
          BIOPORTAL_API_KEY: ${{ secrets.BIOPORTAL_API_KEY }}
          ECOPORTAL_API_KEY: ${{ secrets.ECOPORTAL_API_KEY }}
          AGROPORTAL_API_KEY: ${{ secrets.AGROPORTAL_API_KEY }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
