name: Build Ontologies
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.3.1
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update Git Configuration
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install dependencies
        run: |
          pip install tox

      - name: Create local changes
        id: update
        run: |
          tox -e py
        env:
          BIOPORTAL_API_KEY: ${{ secrets.BIOPORTAL_API_KEY }}
          ECOPORTAL_API_KEY: ${{ secrets.ECOPORTAL_API_KEY }}
          AGROPORTAL_API_KEY: ${{ secrets.AGROPORTAL_API_KEY }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: '🌋 Update build'
          default_author: github_actions
